/**
 * Pricing table JSON
 */

/**
 * Plan groups
 */
export const planGroups = [
  {
    key: 'free',
    name: 'Free',
    desc: 'Free forever, no hidden fees.',
    icon: 'free',
    color: '#69AFB6',
  },
  {
    key: 'travel',
    name: 'Travel',
    desc: 'Improve your travel experience with jet lag management.',
    icon: 'plane',
    color: '#B275CECC',
    isComingSoon: true,
  },
  {
    key: 'life',
    name: 'Life',
    desc: 'For life-lovers who want to prep themselves to get to their best state and stay in their best state, in order to get the best experience of their everyday lives.',
    icon: 'heart',
    color: '#F86783',
  },
  {
    key: 'work',
    name: 'Work',
    desc: 'For ambitious individuals who want to achieve and sustain peak performance through optimal cognitive and physiological performance.',
    icon: 'work',
    color: '#5E7DB3CC',
    darkColor: '#5CAAFD',
  },
];

/**
 * Plan features
 */
export const planFeatures = [
  {
    group: 'baseline',
    title: 'Self Care Baseline Assessments',
    childs: [
      {
        key: 'baseline_lifestyle_performance',
        label: 'Lifestyle Performance',
        desc: 'This assessment determines the mid to long term impacts of your lifestyle behaviors. See how positively or negatively you are affected by your sleep, tobacco consumption, and more.',
      },
      {
        key: 'baseline_metabolic_health',
        label: 'Metabolic Health',
        desc: 'This assessment assesses your risk for metabolic syndrome, a cluster of conditions that raise your risk of heart disease, stroke, diabetes and other serious health problems. Via computer vision, it captures your physical parameters and aggregates it with other clinical variables to compute your metabolic syndrome risk.',
      },
      {
        key: 'baseline_diet_risk',
        label: 'Diet Risk',
        desc: 'This assessment captures the availability or lack of macro nutrients in your diet, your exposure to healthy or unhealthy foods, and your eating habits to determine the health risks you might be getting from your diet.',
      },
      {
        key: 'baseline_chronic_circadian',
        label: 'Chronic Circadian Disruption',
        desc: 'This assessment quantifies the mid to long term disruption that your key lifestyle behaviors (feed-fast cycle, physical activity, and more) are causing to your circadian cycle.',
      },
      {
        key: 'baseline_acute_circadian',
        label: 'Acute Circadian Disruption',
        desc: "This assessment measures the disruption of your resting heart rate's daily fluctuations caused by key lifestyle behaviors and assesses the alignment between your internal body clock and your environmental cues.",
      },
      {
        key: 'baseline_cognitive_health',
        label: 'Cognitive Health',
        desc: 'This assessment assesses your positive and negative psychological conditions that affect your cognitive performance at work and life.',
      },
      {
        key: 'baseline_personality_profile',
        label: 'Personality Profile',
        desc: 'This assessment is a general assessment of your personality across 8 dimensions, through a series of 87 questions.',
      },
    ],
  },
  {
    group: 'wellbeing',
    title: 'Overall Wellbeing Summary',
    childs: [
      {
        key: 'wellbeing_body_health',
        label: 'Body Health',
        desc: 'This is a comprehensive assessment integrating various aspects of your short and long term lifestyle behaviors and previous medical diagnoses to evaluate the quality of your physiological, metabolic, and related body functions.',
      },
      {
        key: 'wellbeing_brain_health',
        label: 'Brain Health',
        desc: 'This is a comprehensive assessment integrating various aspects of your short and long term lifestyle behaviors and previous medical diagnoses to evaluate the quality of your brain functioning and performance, while also taking into account your physiological and metabolic body functions.',
      },
    ],
  },
  {
    group: 'daily',
    title: 'Daily Optimizations',
    childs: [
      {
        key: 'daily_lifestyle_impacts',
        label: 'Daily lifestyle Impacts',
        desc: "Measure the impact of each day's lifestyle behaviors and activities and see how they positively or negatively you.",
      },
      {
        key: 'daily_fatigue_management',
        label: 'Fatigue Management',
        desc: 'See the hourly fluctuations of your fatigue level caused by your sleep and other lifestyle behaviors, and receive a prediction for your fatigue levels each day.',
      },
    ],
  },
  {
    group: 'personal',
    title: 'Personalised Coaching',
    childs: [
      {
        key: 'personal_score_interpretations',
        label: 'Score Interpretations',
        desc: 'A personalised guide to understanding your scores for each assessment, detailing how each contributing factor affects your performance.',
      },
      {
        key: 'personal_goal_recommendations',
        label: 'Goal-based Recommendations',
        desc: 'Insights and suggestions for changes you can make to your lifestyle, generated based on your unique profile, and designed to help you meet your chosen performance objective.',
      },
    ],
  },
  {
    group: 'travel',
    title: 'Travel Wellbeing',
    childs: [
      {
        key: 'travel_jet_lag',
        label: 'Jet Lag Management',
        desc: 'Personalised recommendations to re-align your circadian rhythm and reduce jetlag impact from long-distance travels.',
      },
    ],
  },
];

/**
 * Plans (Separated)
 */
export const plans = [
  // free
  {
    key: 'free_basic_monthly',
    groupKey: 'free_basic',
    backendPlanId: 'Free-USD-Monthly',
    name: 'Free',
    label: '',
    group: 'free',
    color: '#FBFFFF',
    isAnnual: false,
    displayPrice: 'USD 0',
    isFree: true,
    included: {
      baseline_lifestyle_performance: 'Standard',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  {
    key: 'free_basic_annually',
    groupKey: 'free_basic',
    backendPlanId: 'Free-USD-Yearly',
    name: 'Free',
    label: '',
    group: 'free',
    color: '#FBFFFF',
    isAnnual: true,
    displayPrice: 'USD 0',
    isFree: true,
    included: {
      baseline_lifestyle_performance: 'Standard',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  // travel
  {
    key: 'travel_monthly',
    groupKey: 'travel',
    backendPlanId: 'Travel-USD-Monthly',
    name: 'Travel',
    label: '',
    group: 'travel',
    color: '#FBF9FD',
    isAnnual: false,
    displayPrice: 'USD 1.50',
    included: {
      travel_jet_lag: true,
    },
  },
  {
    key: 'travel_annually',
    groupKey: 'travel',
    backendPlanId: 'Travel-USD-Yearly',
    name: 'Travel',
    label: '',
    group: 'travel',
    color: '#FBF9FD',
    isAnnual: true,
    displayPrice: 'USD 15',
    included: {
      travel_jet_lag: true,
    },
  },
  // life-basic
  {
    key: 'life_basic_monthly',
    groupKey: 'life_basic',
    backendPlanId: 'Life-Basic-USD-Monthly',
    name: 'Life Basic',
    label: 'Basic',
    group: 'life',
    color: 'rgba(255, 243, 246, 0.47)',
    isAnnual: false,
    displayPrice: 'USD 3',
    included: {
      baseline_lifestyle_performance: 'Standard',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  {
    key: 'life_basic_annually',
    groupKey: 'life_basic',
    backendPlanId: 'Life-Basic-USD-Yearly',
    name: 'Life Basic',
    label: 'Basic',
    group: 'life',
    color: 'rgba(255, 243, 246, 0.47)',
    isAnnual: true,
    displayPrice: 'USD 30',
    included: {
      baseline_lifestyle_performance: 'Standard',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  // life-advanced
  {
    key: 'life_advanced_monthly',
    groupKey: 'life_advanced',
    backendPlanId: 'Life-Advanced-USD-Monthly',
    name: 'Life Advanced',
    label: 'Advanced',
    group: 'life',
    color: 'rgba(255, 228, 234, 0.47)',
    isAnnual: false,
    displayPrice: 'USD 6',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: true,
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      wellbeing_body_health: true,
      wellbeing_brain_health: true,
      daily_lifestyle_impacts: true,
      daily_fatigue_management: true,
      personal_score_interpretations: true,
      personal_goal_recommendations: true,
    },
  },
  {
    key: 'life_advanced_annually',
    groupKey: 'life_advanced',
    backendPlanId: 'Life-Advanced-USD-Yearly',
    name: 'Life Advanced',
    label: 'Advanced',
    group: 'life',
    color: 'rgba(255, 228, 234, 0.47)',
    isAnnual: true,
    displayPrice: 'USD 60',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: true,
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      wellbeing_body_health: true,
      wellbeing_brain_health: true,
      daily_lifestyle_impacts: true,
      daily_fatigue_management: true,
      personal_score_interpretations: true,
      personal_goal_recommendations: true,
    },
  },
  // work-basic
  {
    key: 'work_basic_monthly',
    groupKey: 'work_basic',
    backendPlanId: 'Work-Basic-USD-Monthly',
    name: 'Work Basic',
    label: 'Basic',
    group: 'work',
    color: 'rgba(211, 227, 255, 0.18)',
    isAnnual: false,
    displayPrice: 'USD 5',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  {
    key: 'work_basic_annually',
    groupKey: 'work_basic',
    backendPlanId: 'Work-Basic-USD-Yearly',
    name: 'Work Basic',
    label: 'Basic',
    group: 'work',
    color: 'rgba(211, 227, 255, 0.18)',
    isAnnual: true,
    displayPrice: 'USD 50',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: 'Once only',
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      daily_lifestyle_impacts: true,
      personal_score_interpretations: true,
    },
  },
  // work-advanced
  {
    key: 'work_advanced_monthly',
    groupKey: 'work_advanced',
    backendPlanId: 'Work-Advanced-USD-Monthly',
    name: 'Work Advanced',
    label: 'Advanced',
    group: 'work',
    color: 'rgba(211, 227, 255, 0.47)',
    isAnnual: false,
    displayPrice: 'USD 15',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: true,
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      wellbeing_body_health: true,
      wellbeing_brain_health: true,
      daily_lifestyle_impacts: true,
      daily_fatigue_management: true,
      personal_score_interpretations: true,
      personal_goal_recommendations: true,
      travel_jet_lag: true,
    },
  },
  {
    key: 'work_advanced_annually',
    groupKey: 'work_advanced',
    backendPlanId: 'Work-Advanced-USD-Yearly',
    name: 'Work Advanced',
    label: 'Advanced',
    group: 'work',
    color: 'rgba(211, 227, 255, 0.47)',
    isAnnual: true,
    displayPrice: 'USD 150',
    included: {
      baseline_lifestyle_performance: 'Full',
      baseline_metabolic_health: true,
      baseline_diet_risk: true,
      baseline_chronic_circadian: true,
      baseline_acute_circadian: true,
      baseline_cognitive_health: true,
      baseline_personality_profile: true,
      wellbeing_body_health: true,
      wellbeing_brain_health: true,
      daily_lifestyle_impacts: true,
      daily_fatigue_management: true,
      personal_score_interpretations: true,
      personal_goal_recommendations: true,
      travel_jet_lag: true,
    },
  },
];
