<template>
  <div id="HowItWorks" class="section-hiw">
    <div class="bg-light">
      <img src="@/assets/images/light-blue-bg.svg" alt="" width="900" height="900">
    </div>

    <!-- title -->
    <div class="container position-relative">
      <div class="row g-0 align-items-center justify-content-center position-relative">
        <div class="col-lg-7">
          <h1 class="font-heading text-center mb-4">
            How It Works
          </h1>
        </div>
      </div>
    </div>

    <!-- points -->
    <div class="section-hiw-sub">
      <div class="container">
        <div class="row g-0 align-items-center justify-content-center position-relative">
          <div class="col-lg-7">
            <h2 class="font-title">
              HOLISTIC,
            </h2>
            <h4 class="font-subtitle">
              AS IT SHOULD BE
            </h4>
            <div class="font-desc mt-4">
              The human body is a complex system with many inter-dependencies, focusing on improvement in only one aspect is not enough.  Only through a holistic approach in targeting your body and mind optimization will you be able to  achieve optimal health.  The science behind it is complex; knowing and analyzing all the data your body is sending is not possible for human to process. We take care of the science and the analytics so that you don’t have to.
            </div>
          </div>
          <div class="col-lg-5">
            <!-- no image -->
          </div>
        </div>
      </div>
    </div>

    <div class="section-hiw-sub">
      <div class="container">
        <div class="row g-0 align-items-center justify-content-center position-relative">
          <div class="col-lg-7">
            <h4 class="font-subtitle">
              NOT JUST DATA,
            </h4>
            <h2 class="font-title">
              BUT ACTIONABLE INSIGHTS
            </h2>
            <div class="font-desc mt-4">
              Copious amount of data without an actionable and contextual plan is of little usefulness.  We convert data generated by your body into easily understandable recommendations that you can follow and act on.
            </div>
          </div>
          <div class="col-lg-5 order-lg-first">
            <!-- no image -->
          </div>
        </div>
      </div>
    </div>

    <div class="section-hiw-sub">
      <div class="container">
        <div class="row g-0 align-items-center justify-content-center position-relative">
          <div class="col-lg-7">
            <h4 class="font-subtitle">
              FOR YOU,
            </h4>
            <h2 class="font-title">
              AND UNIQUELY YOURS
            </h2>
            <div class="font-desc mt-4">
              The context of our priorities in life or work changes from time to time, our body and mind must adapt to that new context if we were to thrive in it. Your very own digital performance coach from Detalytics aligns to that change with your personalized action plan, navigates through the change with you and helps you thrive through it.
            </div>
          </div>
          <div class="col-lg-5">
            <!-- no image -->
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<style lang="less" scoped>
.section-hiw{
  position: relative;
  overflow: hidden;
  background-color: #F0FCFF;
  background-image: linear-gradient(208.51deg, #F2F9FF 25.65%, #F5FAFF 64.97%, #F0FCFF 90.1%);
  padding: 5rem 0;
}
.section-hiw-sub{
  padding: 3rem 0;
}

.font-heading{
  font-size: 3.2rem;
  font-weight: 500;
}
.font-title{
  color: #36898F;
  font-size: 2.5rem;
  font-weight: 600;
}
.font-subtitle{
  color: #36898F;
  font-size: 1.75rem;
  font-weight: 400;
}
.font-desc{
  color: #446366;
}

.bg-light{
  position: absolute;
  top: 50%;
  left: 50%;
  user-select: none;
  pointer-events: none;
  transform: translate(-50%, -60%);
  @media (min-width: @screen-lg) {
    transform: translate(-90%, -50%);
  }
}
</style>
